version: "2"
containers:
- name: vault-server
  image: vault:1.2.3
  cmd: version
  shell: /bin/sh
  ports:
  - 8200
  environment:
    SKIP_SETCAP: "true"
    VAULT_ADDR: http://localhost:8200
    VAULT_TOKEN: root
  memory: 128
